import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';
import Navbar from './components/Navbar';
import SubFooter from './components/SubFooter';
import Footer from './components/Footer';
import SocialMediaSidebar from './components/SocialMediaSidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Trillion Quest',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
<<<<<<< HEAD
        <SocialMediaSidebar />
        <div className="min-h-screen bg-black text-white ">{children}</div>
        <SubFooter />
=======
        <div className="min-h-screen bg-black text-white">{children}</div>
>>>>>>> 47a7f88fe3ce0ccb8352e99dbcab56f0726ec613
        <Footer />
        <SubFooter />
      </body>
    </html>
  );
}
